name: Bug Report
description: File a bug report for this project.
labels: bug/bugfix
type: bug

body:
  - type: markdown
    attributes:
      value: |
        ## Please fill out this form as clearly as possible.
        #### Make sure that you have:
        * Properly described the bug in your title.
        * Given accurate software and hardware specifications where applicable.
        * Given a concise explanation of the bug alongside any steps to reproduce it.
        * Included any relevant logs and configuration files.
  - type: input
    id: version
    attributes:
      label: UZDoom Version
      description: |
        What version are you using?
        Run `uzdoom --version` or check in the console in game.
        Make sure to update to the latest [release](https://github.com/UZDoom/UZDoom/releases) version and test again before continuing.
      placeholder: "UZDoom 4.0.0, git version, branch name, etc."
    validations:
      required: true
  - type: dropdown
    id: gameid
    attributes:
      label: Game
      description: Which game does your bug apply to?
      multiple: false
      options:
        - All
        - Doom
        - Heretic
        - Hexen
        - Strife
      default: 0
  - type: dropdown
    id: OS
    attributes:
      label: Operating System
      description: What operating system are you using?
      multiple: false
      options:
        - Windows 11
        - Windows 10
        - Mac OS
        - Linux x86_64
        - Linux ARM
        - Other
      default: 0
  - type: input
    id: os_detail
    attributes:
      label: OS Version
      description: What is your specific operating system version?
      placeholder: "Windows 11 Home/Pro/Server, Mac OSX version, Debian 10/11, Ubuntu 18/20, Arch, etc."
    validations:
      required: false
  - type: input
    id: hardware
    attributes:
      label: Hardware
      description: What hardware does your computer have?
      placeholder: "CPU, GPU, device brand/model: Intel, AMD, Nvidia, etc"
    validations:
      required: false
  - type: checkboxes
    id: checked
    attributes:
      label: Duplicate Confirmation
      description: Have you checked that no other similar issue already exists?
      options:
        - label: I have searched and not found a similar issue.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe what happens when the bug occurs e.g. if the game crashes, unexpected behaviors, etc. _Include a screenshot if possible._
      placeholder: "The game crashes when..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Replication
      description: What are the steps to reproduce this bug? _Include a small mod demonstrating the bug if possible._
      placeholder: "1. Start by..."
    validations:
      required: false
  - type: textarea
    id: config_file
    attributes:
      label: Configuration
      description: |
        Share the config file(s) you've been using to run the program (`uzdoom.ini`).
        Please avoid pasting the full config, _use attachments or links_ in a [Gist](https://gist.github.com/).
      placeholder: "Example: cl_autorun=true"
      render: ini # syntax highlighting
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      label: Log
      description: |
        Share the relevant log(s) here that were related to the bug.
        Please avoid pasting the full log, _use attachments or links_ in a [Gist](https://gist.github.com/).
      placeholder: "Copy and paste your error log section or provide a link."
    validations:
      required: false
