name: Feature Request
description: Suggest an idea (a new feature or other improvement) for this project.
labels: enhancement
type: feature

body:
  - type: markdown
    attributes:
      value: |
        ## Please fill out this form as clearly as possible.
        #### Make sure that you have:
        * Properly described your feature request in the title.
        * Given a concise description of how it would work/what it would improve.
        * If applicable, adequately explained what problem needs to be solved.
  - type: dropdown
    id: gameid
    attributes:
      label: Game
      description: Which game is your feature request for?
      multiple: false
      options:
        - All
        - Doom
        - Heretic
        - Hexen
        - Strife
      default: 0
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: Problem Description
      description: If applicable, describe the problem your feature is attempting to solve.
      placeholder: I get frustrated when...
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Feature Description
      description: Explain how your feature would work and, if applicable, solve the above problem. Comparisons to existing solutions are encouraged.
      placeholder: How my feature works is...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Media
      description: Any additional content related to your feature request can go here e.g. screenshots or links.
    validations:
      required: false
